-- ==============================================================================
-- ShopPulse AI - TikTok Trend-to-Ad Pipeline Database Schema (PostgreSQL / Supabase)
-- ==============================================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create 'trends' Table
CREATE TABLE IF NOT EXISTS public.trends (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id VARCHAR(128) UNIQUE NOT NULL,             -- TikTok native post ID (deduplication)
    platform VARCHAR(32) DEFAULT 'tiktok' NOT NULL,  -- 'tiktok', 'instagram', 'x', 'reddit'
    trend_title VARCHAR(255) NOT NULL,               -- Generated catchy trend title
    target_category VARCHAR(100) DEFAULT 'General',  -- 'Tech & Gadgets', 'Beauty & Skincare', etc.
    
    -- Viral Metrics
    virality_score INTEGER NOT NULL CHECK (virality_score BETWEEN 1 AND 100),
    views BIGINT DEFAULT 0,
    likes BIGINT DEFAULT 0,
    shares BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    growth_rate VARCHAR(32) DEFAULT '+0%',
    
    -- Audio & Media URLs (Reference only, no expensive rendering stored)
    video_url TEXT,
    audio_url TEXT,
    sound_name VARCHAR(255) DEFAULT 'Trending Audio',
    
    -- Content & Metadata
    caption TEXT,
    hashtags TEXT[] DEFAULT '{}',
    raw_transcript TEXT,                             -- Whisper full speech transcription
    
    -- Marketing & Ad Script Components (Generated by GPT-4o)
    script_hook TEXT NOT NULL,                       -- 0-3s attention-grabbing opening line
    script_body TEXT NOT NULL,                       -- 3-12s core angle & problem-solution
    script_cta TEXT NOT NULL,                        -- 12-15s closing incentive / call-to-action
    why_it_works TEXT,                               -- Psychological breakdown
    
    -- Timestamp & Metadata
    post_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Indexes for High-Performance REST Queries
CREATE INDEX IF NOT EXISTS idx_trends_virality_score ON public.trends (virality_score DESC);
CREATE INDEX IF NOT EXISTS idx_trends_category ON public.trends (target_category);
CREATE INDEX IF NOT EXISTS idx_trends_platform ON public.trends (platform);
CREATE INDEX IF NOT EXISTS idx_trends_created_at ON public.trends (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trends_hashtags ON public.trends USING GIN (hashtags);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.trends ENABLE ROW LEVEL SECURITY;

-- Allow public read access to trends (for frontend dashboard)
CREATE POLICY "Allow public read access to trends" 
ON public.trends 
FOR SELECT 
TO public 
USING (true);

-- Allow service role full access (for backend pipeline inserts/updates)
CREATE POLICY "Allow service role full access" 
ON public.trends 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);
